# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemtodo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
