# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160204_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='findate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
